import type { Metadata } from "next";
import "./globals.css";
import Link from 'next/link' 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="flex justify-center items-center gap-4">
          <Link href={"/"}>home</Link>
          <Link href={"/About"}>about</Link>
          <Link href={"/Contact"}>contact</Link>
          <Link href={"/user"}>user</Link>
          <Link href={"/new"}>new</Link>
          <Link href={"/product"}>product</Link>
          <Link href={"/category"}>category</Link>
          <Link href={"/register"}>register</Link>
          <Link href={"/login"}>login</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
